const typeColors = {
    Normal: "#FFFFFF",
    Fire: "#ff6e00",
    Water: "#4498ff",
    Electric: "#eaff00",
    Grass: "#15ff00",
    Ice: "#03fff2",
    Fighting: "#d20700",
    Poison: "#cc00ff",
    Ground: "#926527",
    Flying: "#97a4d8",
    Psychic: "#F95587",
    Bug: "#c4de00",
    Rock: "#b6aa71",
    Ghost: "#693fa1",
    Dragon: "#6F35FC",
    Dark: "#000000",
    Steel: "#77bebf",
    Fairy: "#fa70ff"
};


const types = {

    Normal: {
        role: "Mediator: The Normal Type naturally occupies the space between extremes. As a mediator, they help maintain cooperation, reduce unnecessary friction, and find reasonable compromises when people or interests clash. This doesn't necessarily mean they're professional peacemakers or constantly solving arguments. More broadly, they have a tendency to keep social situations functional and comfortable. They can understand ordinary perspectives from multiple sides and prefer solutions that everyone can reasonably live with.",
        weapon: "Practicality: For Normal Types, practicality is their primary method of dealing with the world. They don't need elaborate philosophies, radical strategies, or extraordinary abilities to solve problems. They look at what is available, what has worked before, and what can realistically be done.",
        passion: "Comfort: Comfort represents what the Normal Type ultimately wants their life to feel like. They aren't necessarily lazy or hedonistic. Rather, they value a life that feels safe, familiar, pleasant, and emotionally manageable. Their ideal isn't necessarily luxury. It can be something as simple as a stable home, familiar people, predictable routines, enjoyable hobbies, and freedom from unnecessary turmoil.",
        traits: "Balanced, practical, calm, conventional, cooperative, reliable, steady, modest, reasonable, adaptable, sociable, routine-oriented, peaceful, unassuming, pragmatic, conflict-averse, dependable, moderate",

        description: [
            "Normal Types are the steady all-rounders of the world, preferring balance, practicality, and a life free from unnecessary extremes. They rely on common sense and dependable routines, rarely seeking the spotlight or deliberately stirring conflict. Adaptable enough to get along with almost anyone, they progress through patience and consistency rather than extraordinary talent or force. Their greatest strength is their stability, allowing them to remain grounded when others become consumed by passion, ambition, or chaos.",
            "To an unhealthy degree, Normal Types can become excessively conflict-avoidant, conventional, and psychologically dependent on stability. They may suppress individuality, defer to social expectations, and mistake familiarity for safety. Their neutrality can deteriorate into passivity, indecision, and an unwillingness to confront necessary problems. In extreme cases, they may organize their entire existence around avoiding disruption, becoming so invested in appearing reasonable and maintaining harmony that they tolerate dysfunction rather than risk disturbing it.",
            "It is important to note that Normal Types are not necessarily boring, passive, or lacking individuality. Their defining quality is balance and practicality, not an absence of personality. They can be ambitious, eccentric, or highly capable while still preferring ordinary and sensible approaches."
        ]
    },


    Fire: {
        role: "Catalyst: Fire Types bring movement, urgency, and emotional energy into situations that might otherwise remain stagnant. They motivate people through their own passion and willingness to act. They don't necessarily lead through formal authority. Instead, their presence and conviction create momentum. They can inspire others to take risks, speak up, pursue something difficult, or simply stop hesitating.",
        weapon: "Demonstration: Demonstration means Fire Types assert themselves by showing rather than merely telling. They make their convictions visible through action, performance, confrontation, achievement, or emotional expression. This is important because Fire isn't simply passionate internally. Their passion needs an outlet. If they believe they're capable of something, they'll try to prove it. If they're angry, they'll make their anger known. If they believe in an idea, they'll act on it. If they want something, they'll pursue it openly.",
        passion: "Intensity: Intensity is what makes the Fire type feel alive. They crave experiences that carry emotional weight, excitement, passion, challenge, or personal significance. They don't necessarily want constant chaos. What they dislike is emotional flatness. A completely uneventful existence can feel suffocating because Fire wants to feel something strongly. That intensity can manifest as ambition, romance, anger, creativity, competition, adventure, loyalty, or obsession.",
        traits: "Passionate, intense, assertive, expressive, bold, energetic, driven, courageous, competitive, impulsive, emotional, confrontational, enthusiastic, spontaneous, forceful, temperamental, stubborn, reactive",

        description: [
            "Fire Types are passionate warriors who burn intensely in everything they do, wearing their emotions openly and acting on conviction without hesitation. They possess a powerful presence and rarely hesitate to speak their mind, challenge opposition, or throw themselves wholeheartedly into something they believe in. Their determination can make them inspiring and formidable, but their flames burn hot enough to become destructive, causing them to lash out before their temper has time to cool. To a Fire Type, a life without passion is barely a life at all.",
            "To an unhealthy degree, Fire Types can become dominated by impulse, anger, ego, and emotional escalation. Every disagreement can become a contest of wills, every slight a provocation, and every desire an imperative that demands immediate expression. They may confuse intensity with authenticity and aggression with strength, acting before considering consequences and rationalizing destructive behavior as simply \"being honest.\" Their emotional force can become exhausting or frightening when self-control fails.",
            "It is important to note that Fire Types are not necessarily angry, aggressive, or irrational. Their intensity can manifest as enthusiasm, passion, courage, creativity, or devotion just as easily as anger. Their defining trait is emotional force, not hostility. This type is not a diagnosis for Intermittent Explosive Disorder."
        ]
    },


    Water: {
        role: "Facilitator: A facilitator helps people, situations, and groups work together smoothly. Rather than being the person who takes command, they adjust themselves to what others need and help create an environment where everyone can participate. Water Types are naturally suited to filling different roles depending on the circumstances. They can become the listener, supporter, mediator, teammate, or intermediary that a situation happens to require.",
        weapon: "Flexibility: It is how the Water Type navigates obstacles and asserts themselves. Rather than confronting resistance directly, they change their approach until they find a way through it. Their strength comes from having few rigid assumptions about how things must be done. If circumstances change, they can change with them.",
        passion: "Belonging: Belonging is what gives the Water Type a sense of emotional security and fulfillment. They want to feel connected to something or someone, whether that's a friendship group, family, community, relationship, or shared identity. This makes their adaptability more meaningful. They aren't simply changing themselves for the sake of change. They often adapt because being accepted and remaining connected matters deeply to them.",
        traits: "Adaptable, flexible, agreeable, receptive, versatile, accommodating, impressionable, cooperative, fluid, observant, socially aware, easygoing, nonconfrontational, yielding, indecisive, suggestible, dependent, conflict-avoidant",

        description: [
            "Water Types are fluid and adaptable wanderers who rarely feel the need to carve out a fixed identity. They instinctively read the room and adjust themselves to whatever people or circumstances demand, making them versatile companions and remarkably difficult to pin down. Rather than resisting the current, they learn to move with it, finding opportunities wherever circumstances take them. Yet their flexibility can become a weakness when the situation demands conviction, as they may struggle to hold their ground when stronger personalities begin pushing back. ",
            "To an unhealthy degree, Water Types can become so psychologically permeable that they possess little stable identity of their own. They absorb the expectations, opinions, and emotional states of whoever surrounds them, adapting until their own convictions become difficult to distinguish from those of others. Under pressure, they may capitulate, mirror stronger personalities, or change positions to preserve acceptance. Their adaptability can therefore become avoidance of responsibility, producing chronic indecision and an inability to take an unpopular but necessary stand. ",
            "It is important to note that Water Types are not necessarily weak, spineless, or incapable of making decisions. Their adaptability can be a genuine strength, allowing them to navigate changing circumstances and understand different perspectives without becoming rigid. "
        ]
    },

    Grass: {
        role: "Cultivator: The Grass Type contributes by nurturing things into becoming better. They don't necessarily seek to lead or control. Instead, they create the conditions in which people, projects, relationships, or environments can grow naturally.",
        weapon: "Patience: It is the Grass Type's method of overcoming obstacles. They understand that some things cannot be forced into existence. Rather than reacting impulsively, they allow time, preparation, repetition, and consistent effort to do their work.",
        passion: "Harmony: Harmony represents the kind of world the Grass Type wants to inhabit. They are drawn toward balance, peaceful coexistence, and a sense that different parts of life are working together rather than against one another. This extends beyond simply wanting peace. Harmony is about things being healthy and properly integrated: people with their environment, work with rest, ambition with wellbeing, and individuality with community.",
        traits: "Grounded, mindful, patient, organized, deliberate, thoughtful, nurturing, balanced, conscientious, peaceful, disciplined, methodical, observant, reflective, responsible, nature-oriented, composed, growth-oriented",

        description: [
            "Grass Types are patient cultivators who find strength in balance, preparation, and steady growth. They approach life deliberately, tending carefully to their responsibilities while keeping themselves grounded through nature, routine, and thoughtful reflection. Instead of rushing toward immediate results, they prefer to nurture their goals until they have developed into something lasting. Quietly dependable and deeply considerate, they are at their strongest when given something meaningful to cultivate, protect, or improve. ",
            "To an unhealthy degree, Grass Types can become excessively controlled, deliberate, and self-regulating, treating life as something that must constantly be cultivated, organized, and kept in equilibrium. Their mindfulness can become “overanalysis”, their patience can become inertia, and their pursuit of balance can become an obsessive intolerance for disorder. They may spend so much time preparing, considering, and optimizing that spontaneous action becomes psychologically uncomfortable. Their tranquility can conceal a rigid need to keep everything within carefully managed boundaries. ",
            "It is important to note that Grass Types are not necessarily overly peaceful or strictly rigid. Their calmness comes from deliberation and balance, and they can be remarkably persistent or stubborn when protecting something they value. This type is not a diagnosis for Obsessive-Compulsive Personality Disorder."
        ]
    },

    Electric: {
        role: "Entertainer: The Electric Type contributes to society by creating energy and enjoyment for others. They naturally make social environments livelier, whether through humor, enthusiasm, playfulness, storytelling, activity, or simply their presence. The concept of \"entertainer\" doesn't necessarily mean they perform on a stage. It describes someone who instinctively asks: \"How can I make this more fun?\" They break awkward silences, pull people into activities, and prevent situations from becoming stagnant and dull.",
        weapon: "Spontaneity: Spontaneity is how the Electric Type asserts themselves and navigates obstacles. Rather than carefully planning every move, they trust their ability to react quickly and capitalize on whatever appears in front of them. Their strength is momentum.",
        passion: "Excitement: Excitement is what makes the Electric Type feel engaged with life. They crave stimulation, novelty, movement, and experiences that produce a strong sense of energy. Novelty is the main element that can satisfy them: trying something new, meeting someone interesting, going somewhere unfamiliar, playing games, discovering a new hobby, or suddenly changing plans.",
        traits: "Energetic, lively, playful, spontaneous, adventurous, enthusiastic, curious, impulsive, restless, excitable, sociable, humorous, thrill-seeking, optimistic, expressive, quick-moving, novelty-seeking, easily stimulated",

        description: [
            "Electric Types are restless sparks of energy who thrive on excitement, novelty, and constant movement. They chase experiences with infectious enthusiasm, turning even ordinary situations into opportunities for fun, adventure, or spontaneous chaos. Their playful personalities make them natural sources of energy within a party, always ready to shake things up when life becomes too predictable. Yet their hunger for stimulation can make stillness feel unbearable, leaving them perpetually searching for the next thrill.",
            "To an unhealthy degree, Electric Types become dependent on constant stimulation and increasingly unable to tolerate stillness. They chase novelty, excitement, social activity, entertainment, and spontaneous experiences in an almost compulsive cycle, quickly abandoning anything that becomes predictable or demanding. Their enthusiasm becomes impulsivity, restlessness, and poor tolerance for delayed gratification. They may continually manufacture excitement simply to avoid boredom, reflection, or the uncomfortable realization that constant movement has become a substitute for genuine direction. ",
            "It is important to note that Electric Types are not hyperactive or incapable of taking anything seriously. Their energy comes from curiosity and stimulation, and they can channel it into creativity, exploration, competition, or passionate pursuits. This type is not a diagnosis for Attention Deficit Hyperactivity Disorder."
        ]
    },

    Ice: {
        role: "Analyst: The analyst contributes by examining, interpreting, and clarifying. Ice Types naturally become the person others turn to when something needs to be understood rather than merely experienced. They observe situations from a distance, separate relevant information from emotional noise, and identify patterns, inconsistencies, or underlying causes.",
        weapon: "Logic: Logic is the Ice Type's primary means of asserting themselves and overcoming obstacles. Rather than relying on force, emotion, social charm, or authority, they make their position difficult to challenge by constructing a rational argument. Their strength lies in being able to separate what feels true from what can actually be demonstrated.",
        passion: "Understanding: Understanding is what ultimately drives the Ice Type's curiosity. They aren't satisfied with merely knowing what happened. They want to know why it happened, how it works, and what lies underneath it. This can manifest in anything from science and philosophy to psychology, mathematics, strategy, technology, or abstract subjects.",
        traits: "Analytical, detached, logical, rational, precise, direct, composed, objective, intellectual, skeptical, efficient, observant, disciplined, reserved, unemotional, critical, calculating, clarity-oriented",

        description: [
            "Ice Types are cool-headed analysts who keep emotion at arm's length in pursuit of clarity and reason. They observe situations carefully, dissect problems logically, and speak with a blunt precision that leaves little room for ambiguity. Difficult circumstances rarely shake their composure, as they prefer to understand a problem before allowing themselves to react to it. Their intellect makes them formidable strategists, though their emotional distance can sometimes leave others wondering whether anything can truly reach them. ",
            "To an unhealthy degree, Ice Types become so detached from emotion that they begin treating human experience as an inconvenient variable in an otherwise rational system. Their preference for clarity becomes bluntness, emotional invalidation, and intellectual superiority, with compassion dismissed as irrational interference. They may dissect people's motives accurately while remaining profoundly unwilling to engage with their emotional consequences. Over time, their composure can become emotional isolation, with distance mistaken for objectivity and coldness mistaken for intellectual strength. ",
            "It is important to note that Ice Types are not necessarily emotionless, heartless, or incapable of caring. Their detachment describes how they process situations, not whether they experience emotions. They may feel deeply while still choosing to approach decisions rationally. This type is not a diagnosis for Schizoid Personality Disorder."
        ]
    },


    Fighting: {
        role: "Champion: A champion is someone who stands up for a cause, person, principle, or community. Fighting Types naturally take the role of the person who steps forward when something needs defending. It's not that they want to be the leader. Their role is more specifically to represent and defend what they believe is right.",
        weapon: "Bravery: It is the Fighting Type's primary means of asserting themselves against adversity. Their strength isn't simply physical power. It is their willingness to act despite fear, uncertainty, or personal risk. This distinction is important though: bravery doesn't mean they aren't afraid. It means fear doesn't automatically stop them.",
        passion: "Honor: Honor represents the standard by which the Fighting Type wants to live. They don't merely want to win. They want to be able to respect how they won. Honor gives their strength a moral framework. It creates rules around when and why their power should be used.",
        traits: "Courageous, disciplined, principled, protective, resolute, honorable, steadfast, physically capable, determined, brave, responsible, cautious, vigilant, self-controlled, competitive, dutiful, resilient, justice-oriented",

        description: [
            "Fighting Types are disciplined champions who meet adversity head-on and refuse to abandon their principles when challenged. They possess courage, physical determination, and a strong sense of honor, treating strength as something that carries responsibility rather than merely a means of domination. Though willing to fight, they are not reckless, carefully judging risks and protecting themselves and others before committing to action. Their greatest victories come not simply from overpowering their opponents, but from proving that conviction can withstand pressure. ",
            "To an unhealthy degree, Fighting Types become psychologically organized around struggle, endurance, and proving themselves through adversity. They may begin interpreting ordinary disagreements as tests of character and compromise as weakness, creating conflict simply because conflict provides something against which to measure themselves. Their code of honor can become rigid moral absolutism, while their protective instincts can become controlling or paternalistic. They may tolerate extraordinary amounts of suffering while simultaneously demanding that everyone around them demonstrate the same toughness. ",
            "It is important to note that Fighting Types are not necessarily aggressive or eager to fight. Their defining quality is courage guided by principle. They may actually avoid unnecessary conflict because they understand the responsibility that comes with their strength. "
        ]
    },


    Poison: {
        role: "Opportunist: The Poison Type naturally looks for openings, advantages, and weaknesses within their environment. Rather than trying to maintain harmony or uphold a particular system, they ask what can be gained from the situation and how circumstances can be turned in their favor. As a social role, the opportunist is someone who navigates the existing environment rather than trying to change it. They notice who has influence, who is vulnerable, what people want, and where an opportunity might appear.",
        weapon: "Manipulation: Manipulation represents the Poison Type's preferred method of exerting influence without relying on direct confrontation. They understand that people have desires, fears, insecurities, loyalties, and expectations, and they know how these can be used to influence behavior. This must not be strictly linked with refined skills of manipulation, the Poison Type's main exhibition of their weapon is to attempt at manipulation, results and processes vary from the individual.",
        passion: "Survival: Survival is the deepest motivation underneath the Poison Type's behavior. Their desire isn't necessarily simply to \"win.\" It is to remain safe, independent, and capable of protecting themselves. This makes their harshness more understandable within the archetype. Cruelty, emotional distance, independence, and suspicion can all function as defensive mechanisms. They would rather be prepared for danger than assume the world will treat them kindly.",
        traits: "Self-reliant, perceptive, guarded, pragmatic, calculating, independent, opportunistic, harsh, self-interested, defensive, suspicious, socially aware, strategic, resourceful, distrustful, manipulative, survival-oriented, security-conscious",

        description: [
            "Poison Types are hardened survivors who navigate society by reading people, identifying threats, and protecting their own interests above all else. They understand social dynamics instinctively and are willing to exploit weaknesses, manipulate circumstances, or put up a harsh exterior when it keeps them safe. Independence is their preferred armor, though they are perfectly willing to rely on others when doing so provides greater security. They rarely assume the world will treat them kindly, so they make sure they are prepared to bite first when they sense danger. ",
            "To an unhealthy degree, Poison Types become excessively self-protective, distrustful, and instrumental in their relationships. Their awareness of social dynamics may develop into constant calculation, where interactions are evaluated primarily in terms of threats, leverage, resources, or personal advantage. Dependence may be rejected when it implies vulnerability but embraced when another person can provide security, creating relationships based more on utility than mutuality. Their defensive harshness can become cruelty, with emotional detachment serving to justify behavior that harms others.",
            "It is important to note that Poison Types are not necessarily evil, cruel, or incapable of caring about others. Their harshness often functions as a defensive strategy rooted in self-preservation. They can form strong attachments, particularly when they feel someone provides genuine safety or loyalty. This type is not a diagnosis for Antisocial Personality Disorder."
        ]
    },


    Ground: {
        role: "Guide: A Ground Type naturally takes on the role of directing, instructing, and keeping others on the right path. They tend to trust experience, established standards, and practical knowledge, making them useful when people need clear direction rather than endless possibilities. They provide a reliable sense of direction.",
        weapon: "Authority: Authority is how Ground Types assert themselves and establish their position. Rather than persuading through charm or adapting to others, they create influence through confidence, rules, expertise, responsibility, and established standards. Their authority comes from the belief that someone needs to take charge and maintain order.",
        passion: "Security: It is what Ground Types ultimately want to build and preserve. They want a world where things are dependable, predictable, and protected from unnecessary instability. Unlike the Normal Type's Comfort, which focuses on feeling at ease, Ground's Security focuses on being protected and prepared.",
        traits: "Practical, realistic, structured, disciplined, authoritative, confident, reliable, responsible, organized, cautious, traditional, rule-oriented, experienced, decisive, commanding, conservative, methodical, security-conscious",

        description: [
            "Ground Types are steadfast guardians of order who believe that a strong world requires structure, standards, and people willing to uphold them. Practical and experienced, they prefer proven methods over reckless experimentation and are naturally comfortable taking responsibility for others. Their authority comes from confidence, consistency, and an ability to establish boundaries that others can rely upon. They make dependable leaders and protectors, though their attachment to stability can make unfamiliar ideas and sudden changes difficult to embrace. ",
            "To an unhealthy degree, Ground Types become rigid authoritarian personalities obsessed with order, hierarchy, and predictability. They place excessive trust in established rules and personal experience, becoming resistant to novelty even when circumstances demand adaptation. Their leadership can become controlling, their caution obstructionist, and their realism a justification for dismissing unfamiliar possibilities before genuinely considering them. ",
            "It is important to note that Ground Types are not necessarily boring, stubborn, or authoritarian. Their preference for structure reflects a desire for stability and reliability. They can be flexible when circumstances provide sufficient evidence that change is necessary. "
        ]
    },


    Flying: {
        role: "Adventurer: The Flying Type contributes by expanding people's horizons. As an adventurer, they are drawn toward new places, experiences, ideas, and ways of living, often encouraging others to step outside what they already know. It isn't demonstrated through the literal sense of adventure, so this doesn't require literal travel. An adventurer can be someone who constantly explores ideas, creative possibilities, experiences, or unconventional lifestyles.",
        weapon: "Imagination: Imagination is how the Flying Type asserts themselves against limitations. Rather than relying primarily on force, discipline, or practicality, they overcome obstacles by envisioning alternatives. Their imagination allows them to mentally escape constraints before physically overcoming them. They can see what something could become, not merely what it currently is.",
        passion: "Possibility: It is what makes the Flying Type feel alive. They are energized by the feeling that something new, exciting, or extraordinary could happen. They don't necessarily need certainty: uncertainty can be part of the appeal, because an unknown future contains countless potential paths.",
        traits: "Imaginative, adventurous, idealistic, optimistic, energetic, daring, creative, visionary, spontaneous, freedom-loving, curious, expressive, enthusiastic, romantic, restless, exploratory, aspirational, possibility-oriented",

        description: [
            "Flying Types are adventurous dreamers who see the world as a landscape of endless possibilities rather than fixed limitations. Guided by imagination and ideals, they chase distant horizons with optimism, enthusiasm, and a willingness to take risks. They inspire others by imagining what could exist beyond the boundaries of the present, often acting before reality has had a chance to tell them no. Their greatest gift is the ability to make the impossible feel within reach, though they can sometimes become so captivated by the dream that they forget to look at the ground. ",
            "To an unhealthy degree, Flying Types become increasingly detached from practical reality, living according to fantasies, ideals, possibilities, and imagined futures. Their optimism can become denial, while their imagination becomes an escape from limitations they refuse to acknowledge. They may continually pursue the next dream, adventure, or grand possibility without developing the discipline required to sustain any of them. Their need for freedom can become an inability to tolerate commitment, responsibility, or grounding, leaving them perpetually in pursuit of a life that exists more vividly in imagination than in reality. ",
            "It is important to note that Flying Types are not necessarily childish, unrealistic, or irresponsible. Their idealism and imagination can inspire genuine innovation, courage, and exploration. Seeing possibilities others overlook is not the same as being detached from reality. This type is not a diagnosis for Attention Deficit Hyperactivity Disorder or Bipolar Disorder."
        ]
    },


    Psychic: {
        role: "Seer: The Psychic Type acts as the observer and interpreter of the group. They notice patterns, motives, possibilities, and underlying meanings that others may overlook. Rather than leading through force, they provide perspective and guidance. A seer doesn't necessarily predict the future literally. The role can manifest as someone who is intuitive, insightful, philosophical, perceptive, or unusually good at understanding people and situations.",
        weapon: "Influence: Psychic Types don't necessarily assert themselves through physical strength, authority, or confrontation. Their power comes from their ability to affect how other people think, feel, and perceive situations. Influence can be gentle and benevolent, such as guidance or persuasion, but it can also become manipulative when their understanding of others is used selfishly.",
        passion: "Esotericism: Esotericism represents the Psychic Type's fascination with knowledge that lies beyond ordinary understanding. They aren't satisfied with only what is immediately visible or practical. They want to investigate hidden systems, mysteries, symbols, consciousness, spirituality, metaphysics, psychology, and abstract ideas. This is less about being \"magical\" and more about a desire to understand what lies beneath the surface of reality.",
        traits: "Intelligent, intuitive, contemplative, perceptive, composed, insightful, curious, analytical, philosophical, introspective, patient, strategic, observant, mentally agile, mysterious, persuasive, subtle, intellectually driven",

        description: [
            "Psychic Types are contemplative sages who possess a quiet intelligence and an instinct for seeing what lies beneath the surface. Calm even under pressure, they spend their time exploring abstract ideas, hidden patterns, mysteries, and the workings of the mind. Rather than commanding others openly, they influence through insight, subtly guiding decisions with carefully chosen words and observations. They are the kind of adventurers who seem to know more than they say, leaving others wondering whether their wisdom comes from intellect, intuition, or something stranger. ",
            "To an unhealthy degree, Psychic Types become excessively cerebral and psychologically preoccupied. They analyze motives, hidden meanings, interpersonal dynamics, and abstract possibilities until ordinary interactions become elaborate mental puzzles. Their insight can develop into suspicion, their intuition into certainty without evidence, and their influence into subtle psychological control. They may become convinced that they understand people better than those people understand themselves. Rather than openly demanding control, they attempt to shape situations indirectly, preferring to manipulate the mental environment around them. ",
            "It is important to note that Psychic Types are not necessarily incredibly smart, mysterious, manipulative, or socially distant. They also do not necessarily possess hidden or forbidden knowledge. Their introspection and intuition can simply reflect a naturally contemplative mind. Their influence may come from wisdom and insight rather than a desire to control others. This type is not a diagnosis for any disorder on the schizophrenia spectrum."
        ]
    },


    Bug: {
        role: "Specialist: Bug Types contribute through narrow but unusually deep knowledge. They aren't necessarily the person everyone notices first. Instead, they become valuable because they've spent time understanding something obscure, overlooked, technical, strange, or highly specific. A specialist doesn't need to know everything. They know a lot about something other people barely understand.",
        weapon: "Unpredictability: For Bug Types, unpredictability is their means of asserting individuality and navigating the world. They don't necessarily overpower people or persuade them. Instead, they're difficult to anticipate because their thoughts, interests, reactions, and methods don't always follow conventional patterns. Their advantage comes from not being easily figured out.",
        passion: "Discovery: Discovery is what gives Bug Types their sense of curiosity and excitement. They are drawn toward things that are hidden, obscure, unexplored, forgotten, or simply strange. They don't necessarily seek adventure in the conventional sense. Their adventure can happen entirely inside a room with a computer, an old book, a collection, a hobby, or some bizarre subject nobody else cares about.",
        traits: "Reserved, discreet, unconventional, observant, curious, eccentric, introverted, unpredictable, specialized, knowledgeable, inventive, private, peculiar, independent, experimental, detail-oriented, obscure, socially withdrawn",

        description: [
            "Bug Types are elusive specialists who prefer the shadows to the spotlight, quietly cultivating strange interests and obscure knowledge that few others bother to pursue. Their reserved exterior conceals an unpredictable inner world filled with eccentric ideas, unusual fascinations, and unexpected connections. They may remain silent for long periods before suddenly revealing an insight nobody else considered. Difficult to understand and even harder to predict, they are the party members who seem insignificant until they casually reveal that they know something everyone else desperately needed to know. ",
            "To an unhealthy degree, Bug Types retreat almost completely into private interests, obscure knowledge, and an internal world that few others can access. Their individuality becomes alienation, secrecy, eccentricity, and difficulty communicating with people outside their narrow areas of interest. They may cultivate knowledge partly as a refuge from social exposure, becoming disproportionately confident within specialized domains while remaining deeply uncomfortable with ordinary interpersonal demands. Their unpredictability can become erratic behavior, deliberate obscurity, or an almost reflexive rejection of anything perceived as conventional. ",
            "It is important to note that Bug Types are not necessarily unintelligent, socially incapable, or simply strange for the sake of being strange. Their reserved nature can conceal considerable expertise, creativity, and highly developed interests that only become visible when they choose to share them. This type is not a diagnosis for Autism Spectrum Disorder."
        ]
    },


    Rock: {
        role: "Anchor: An anchor is someone who provides stability and reliability when circumstances become difficult or uncertain. Rock Types tend to be the people others can depend on when things stop being easy. They don't necessarily want to lead from the front like the Ground Type. Their value comes from being difficult to shake. They help others stay grounded by offering a steady presence and a realistic perspective.",
        weapon: "Endurance: Endurance is the Rock Type's primary method of overcoming obstacles. They don't necessarily need to overpower a problem immediately. Instead, they outlast it. Their strength comes from persistence, resilience, and the willingness to keep going when circumstances become uncomfortable or exhausting.",
        passion: "Realism: Realism represents what Rock Types are fundamentally drawn toward: seeing and accepting reality as it actually is. They don't particularly need comforting illusions, idealized possibilities, or elaborate explanations. There is satisfaction in stripping away exaggeration and dealing with concrete facts. Their realism gives them a sense of clarity and control because they would rather confront an unpleasant truth than build their life around a pleasant fiction.",
        traits: "Resilient, direct, honest, realistic, practical, determined, steadfast, confident, blunt, enduring, straightforward, tough, unsentimental, grounded, self-reliant, persistent, stoic, no-nonsense",

        description: [
            "Rock Types are people who meet reality without flinching and refuse to be broken by adversity. Direct and uncompromising, they value honesty over politeness and practicality over comforting illusions, cutting through unnecessary complexity to deal with what is actually in front of them. They possess an enduring confidence that allows them to stand firm when circumstances become difficult. Where others might bend, retreat, or dream of another outcome, the Rock Type plants their feet and deals with the problem as it exists. ",
            "To an unhealthy degree, Rock Types become emotionally hardened and psychologically inflexible, treating vulnerability, uncertainty, and idealism as weaknesses. Their realism becomes cynicism, their honesty becomes brutality, and their resilience becomes an inability to acknowledge exhaustion or ask for help. They may pride themselves on being impossible to break while gradually becoming impossible to reach. ",
            "It is important to note that Rock Types are not necessarily crude, emotionally insensitive, or incapable of adapting. Their bluntness comes from a preference for clarity and realism. They can care deeply while simply expressing that care in practical rather than sentimental ways. "
        ]
    },


    Ghost: {
        role: "Trickster: The Ghost Type's social function is to entertain, disrupt expectations, and make people see things differently. They keep social situations interesting by introducing humor, surprises, absurdity, and clever provocations. Their presence can make people laugh while also keeping them slightly uncertain about what they'll do next. They may deliberately play with expectations, tease others, tell strange stories, or turn uncomfortable subjects into jokes.",
        weapon: "Wit: Wit is how the Ghost Type asserts themselves and gains leverage over situations. Rather than relying on physical strength or direct authority, they use cleverness, timing, humor, wordplay, and psychological observation. Their intelligence is expressed socially. A Ghost Type may not necessarily be the most academically intellectual person in the room, but they can be extremely good at knowing what to say, when to say it, and how it will affect someone.",
        passion: "Nostalgia: Nostalgia gives the Ghost Type's playfulness an emotional foundation. They aren't simply obsessed with jokes and entertainment. They are often deeply attached to things that have already passed: childhood, old places, forgotten media, past relationships, traditions, memories, or moments that can never quite be recreated. This creates an interesting contradiction. They may constantly joke and act playful in the present while being psychologically drawn toward the past.",
        traits: "Whimsical, imaginative, nostalgic, witty, playful, mysterious, eccentric, melancholic, secretive, cunning, mischievous, humorous, theatrical, emotionally guarded, sentimental, unpredictable, vengeful, resentful",

        description: [
            "Ghost Types are eccentric tricksters haunted by the past, blending whimsical humor with nostalgia, mystery, and an occasionally unsettling edge. They delight in entertaining others through clever jokes, strange antics, and unexpected surprises, often turning melancholy into something strangely charming. Beneath that playful exterior, however, they can carry old wounds with remarkable persistence, remembering betrayals long after others have forgotten them. Their presence is both amusing and eerie, like someone telling jokes from the other side of a grave while quietly keeping a list of everyone who ever wronged them. ",
            "To an unhealthy degree, Ghost Types become excessively preoccupied with the past, resentment, and emotional wounds. Nostalgia may become fixation, with old experiences repeatedly reconstructed, romanticized, or used to define the present. Their humor can become defensive and cynical, allowing them to disguise vulnerability through irony, mockery, or deliberately unsettling behavior. When hurt, they may preserve grievances rather than metabolize them, treating forgiveness as surrender and retaliation as emotional resolution. Their mysteriousness can become deliberate emotional inaccessibility, while their playfulness can conceal a considerable amount of hostility.",
            "It is important to note that Ghost Types are not necessarily depressed, creepy, or obsessed with the past. Their connection to nostalgia can be playful, creative, and affectionate. Their darker or resentful side is only one expression of their tendency to hold onto emotionally significant experiences and mostly only occurs if the Ghost Type has been wounded in the past. This type is not a diagnosis for depression."
        ]
    },


    Dragon: {
        role: "Emperor: The Dragon Type naturally occupies the highest position in a hierarchy. They don't merely lead others. They see themselves as someone who should set the direction, establish standards, and possess the authority to determine what happens. Their leadership tends to be hierarchical rather than collaborative. They expect competence, loyalty, and respect from those beneath them, while feeling responsible for maintaining the strength and status of whatever they rule over.",
        weapon: "Domination: Domination is the Dragon Type's method of asserting their will. They don't primarily persuade, adapt, compromise, or quietly endure. They establish their position by making their presence difficult to ignore. This can manifest through authority, intimidation, competition, status, overwhelming confidence, or sheer force of personality. The important part is that the Dragon wants the surrounding environment to bend toward their will.",
        passion: "Power: Power is what the Dragon Type ultimately craves and finds fulfilling. They want the ability to shape circumstances, command respect, accomplish extraordinary things, and stand in a position where their choices have significant consequences. Power isn't necessarily just political or physical power. It can mean status, influence, wealth, achievement, authority, capability, or personal supremacy.",
        traits: "Commanding, authoritative, ambitious, proud, intense, ruthless, demanding, elitist, intimidating, confident, dominant, imperious, competitive, uncompromising, charismatic, prestigious, grandiose, status-conscious",

        description: [
            "Dragon Types are commanding titans who carry themselves with an unmistakable sense of power, superiority, and destiny. They set immense standards for themselves and others, pursuing their ambitions with ruthless determination and little patience for those they consider incapable of meeting them. Their presence alone can dominate a room, combining confidence, intensity, and an almost regal authority. They do not merely want to succeed; they want to become someone whose strength and accomplishments make their superiority impossible to ignore.",
            "To an unhealthy degree, Dragon Types can become grandiose, domineering, and excessively hierarchical, organizing their worldview around superiority and inferiority. They may regard respect as something inherently owed to them and interpret resistance as an insult requiring punishment or submission. Their ambition can become insatiable because ordinary success no longer satisfies the need to feel exceptional. They may surround themselves with people who reinforce their status while dismissing criticism as evidence of inferiority, creating an increasingly insulated worldview in which dominance becomes both their identity and primary measure of worth.",
            "It is important to note that Dragon Types are not necessarily arrogant, tyrannical, or cruel. Their commanding presence and high standards can instead manifest as confidence, leadership, ambition, and a desire to achieve something extraordinary. This type is not a diagnosis for Narcissistic Personality Disorder."
        ]
    },


    Dark: {
        role: "Rebel: The Dark Type occupies the role of the outsider, dissenter, or challenger. They question established rules and social expectations rather than accepting them simply because they are customary. As a rebel, they disrupt systems, challenge authority, and expose or exploit weaknesses in conventions. They don't necessarily want to replace every system with something better. Sometimes, the act of refusing to conform is itself the point. This isn't necessarily rooted from a desire to break the rules and oppose anything; it can happen that the Dark Type's motive is to protect the ones vulnerable against the authority.",
        weapon: "Savagery: Savagery represents how the Dark Type asserts themselves when faced with resistance. Their approach is raw, ruthless, and deliberately intimidating. Rather than negotiating their way around opposition, they are willing to confront it aggressively. Importantly, \"savagery\" doesn't have to mean literal physical violence. It can describe a brutal attitude: merciless criticism, intimidation, ruthless competition, psychological pressure, or deliberately crossing boundaries.",
        passion: "Defiance: Defiance is the emotional engine underneath the archetype. Dark Types feel most alive when they are resisting something, breaking through restrictions, or proving that nobody has the right to dictate their behavior. Unlike Comfort for Normal Types, Defiance isn't about creating a pleasant state. It's about experiencing the freedom of resistance.",
        traits: "Defiant, rebellious, ruthless, provocative, fearless, unpredictable, cynical, transgressive, confrontational, apathetic, irreverent, aggressive, calculating, uncompromising, rebellious, boundary-testing, chaotic, intimidating",

        description: [
            "Dark Types are rebellious provocateurs who reject conventional morality and take pleasure in challenging boundaries that others consider untouchable. They thrive in confrontation, refuse to be easily intimidated, and are willing to employ deception, brutality, or underhanded tactics when pursuing their objectives. Rather than fearing chaos, they often embrace it as a source of freedom and opportunity. They are unpredictable precisely because they have little interest in playing by the rules everyone else assumes they should follow.",
            "To an unhealthy degree, Dark Types become deliberately cruel, brutal, antagonistic, and contemptuous of conventional restraints, treating transgression itself as proof of independence. They may provoke conflict simply to demonstrate that they cannot be controlled, while increasingly escalating their behavior when ordinary rebellion stops producing the desired sense of power. Their rejection of morality can become indifference toward consequences, including consequences to themselves. In extreme forms, they may develop an adversarial relationship with society in which destruction, intimidation, and violation become more important than whatever original principle motivated their rebellion. ",
            "It is important to note that Dark Types are not necessarily evil, immoral, or violent as they are well capable of caring about people. Their defining quality is defiance toward conventional constraints, not an inherent desire to cause harm. A Dark Type can be rebellious, provocative, or unconventional without being malicious. This type is not a diagnosis for Opposant Defiant Disorder, Conduct Disorder or Antisocial Personality Disorder."
        ]
    },


    Steel: {
        role: "Achiever: The Steel Type naturally takes on the role of the person who sets goals, raises standards, and gets results. Their value to others comes from competence and accomplishment. They are often the ones who take responsibility for difficult tasks because they want to prove that they can meet, or exceed, the expected standard.",
        weapon: "Perfectionism: Perfectionism is the Steel Type's primary method of asserting control and superiority. They don't simply try to complete something. They refine it, inspect it, correct it, and push it toward an ideal standard.",
        passion: "Mastery: Mastery is what ultimately makes the Steel Type feel fulfilled. Achievement gives them results, but mastery gives those results meaning. They don't merely want to win once. They want to understand the craft deeply enough that excellence becomes repeatable. This makes their ambition somewhat different from simple status-seeking. The real satisfaction comes from becoming better than they were before.",
        traits: "Meticulous, perfectionistic, disciplined, competitive, diligent, precise, ambitious, persistent, hardworking, demanding, methodical, attentive, rigorous, self-critical, achievement-oriented, focused, exacting, improvement-oriented",

        description: [
            "Steel Types are relentless perfectionists who pursue mastery with almost mechanical dedication. Every flaw becomes something to correct, every weakness another challenge to overcome, and every achievement merely another benchmark to surpass. Meticulous and competitive, they devote extraordinary amounts of time to refining their abilities and will often compete as fiercely against themselves as they do against everyone around them. They are terrifyingly persistent once they have chosen a goal, because for them, excellence is not a destination but an endlessly moving target. ",
            "To an unhealthy degree, Steel Types become excessively perfectionistic, compulsive, and achievement-oriented, evaluating themselves almost entirely through performance. Minor errors may become disproportionately significant, producing chronic dissatisfaction regardless of actual competence. Their competitive drive can turn every activity into a ranking system, including areas that do not inherently require competition. Rest may be interpreted as laziness, while self-worth becomes contingent upon productivity and improvement. Their attention to detail can develop into debilitating overcontrol and inability to delegate.",
            "It is important to note that Steel Types are not necessarily cold, perfectionistic machines who care only about winning. Their pursuit of excellence can come from genuine craftsmanship, pride, discipline, or a desire to improve themselves rather than simply defeat others. This type is not a diagnosis for Obsessive Compulsive Disorder."
        ]
    },


    Fairy: {
        role: "Enchanter: The enchanter is someone who draws people in. Fairy Types create an emotional atmosphere, make others feel noticed, and can turn an ordinary social environment into something more colorful and engaging. Their contribution isn't necessarily leadership or guidance. Instead, they make people feel something. They entertain, charm, comfort, intrigue, and sometimes bewilder those around them.",
        weapon: "Charm: Charm is the Fairy Type's method of getting through people's defenses. Rather than forcing someone to cooperate, they make cooperation feel appealing. Their power lies in presentation, emotional intelligence, charisma, playfulness, and knowing exactly how to approach different personalities. They can soften hostility, gain trust, or redirect someone's attention simply through how they interact with them.",
        passion: "Amusement: Amusement is what makes the Fairy Type feel alive. They enjoy experiences that are entertaining, emotionally stimulating, playful, strange, or surprising. This doesn't directly mean they're constantly seeking laughter. \"Amusement\" is broader: they enjoy the pleasure of playing with situations and people, seeing reactions, creating memorable moments, and injecting novelty into everyday life.",
        traits: "Charming, joyful, warm, whimsical, emotionally intelligent, playful, charismatic, affectionate, sociable, cunning, mischievous, persuasive, manipulative, perceptive, theatrical, enchanting, provocative, sadistic",

        description: [
            "Fairy Types are enchanting social creatures who captivate others through warmth, emotional intelligence, humor, and an almost magical sense of charm. Their cheerful and innocent exterior makes them easy to approach, but beneath it lies a clever and playful mind that enjoys manipulating expectations and turning social situations into games. They can be genuinely caring while simultaneously delighting in teasing, tricking, or unsettling others simply for amusement. Their sweetness is real, but so is the little gleam in their eye when they realize they've found exactly the button to push. ",
            "To an unhealthy degree, Fairy Types can become extremely socially calculating beneath an outwardly affectionate and playful presentation, using charm to lower defenses and emotional intelligence to identify vulnerabilities. Their warmth may become instrumental rather than reciprocal, with relationships treated as opportunities for influence, entertainment, or control. They can derive gratification from manipulating reactions, embarrassing others, or testing how far their charm allows them to push boundaries. In their darkest form, their cheerful presentation becomes a deliberate mask, allowing cruelty to be delivered playfully and making it difficult for others to distinguish genuine affection from calculated amusement.",
            "It is important to note that Fairy Types are not necessarily innocent, gentle, or purely benevolent. Their warmth and cheerful nature can make them appear harmless, but this does not mean they lack cunning, selfishness, or darker impulses. Their emotional intelligence can be used for genuine care just as easily as manipulation, and their playful behavior may sometimes conceal a sharp or even cruel streak beneath the surface. This also does not imply they are necessarily ill-mannered on the inside, they are still capable of pure kindness and generosity."
        ]
    }

};
